# Generated by Django 5.0.2 on 2024-02-08 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuId', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('menuImgUrl', models.TextField(default=None, null=True)),
                ('status', models.IntegerField(default=1, max_length=1)),
                ('storeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('optionId', models.BigAutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('status', models.IntegerField(default=1, max_length=1)),
                ('menuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.menu')),
                ('contents', models.ManyToManyField(to='kiosk.optioncontent')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartId', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(max_length=1)),
                ('menuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.menu')),
                ('optionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.option')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.BigAutoField(primary_key=True, serialize=False)),
                ('pay', models.CharField(max_length=255)),
                ('totalPrice', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('menuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.menu')),
                ('optionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.option')),
            ],
        ),
    ]
