# Generated by Django 5.0.2 on 2024-02-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_optioncontent_menu_option_cart_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Store'},
        ),
    ]
