# Generated by Django 5.0.2 on 2024-02-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_alter_store_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='menuId',
        ),
        migrations.AddField(
            model_name='menu',
            name='optionId',
            field=models.ManyToManyField(to='kiosk.option'),
        ),
    ]
