# Generated by Django 5.0.2 on 2024-02-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_remove_option_menuid_menu_optionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menuImgUrl',
            field=models.TextField(blank=True, null=True),
        ),
    ]
