# Generated by Django 5.0.2 on 2024-02-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0005_alter_menu_menuimgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optioncontent',
            name='content',
        ),
        migrations.AddField(
            model_name='optioncontent',
            name='buttonContent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='optioncontent',
            name='intContent',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
