# Generated by Django 5.0.2 on 2024-02-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_remove_optioncontent_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optioncontent',
            old_name='buttonContent',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='optioncontent',
            name='intContent',
        ),
    ]
