# Generated by Django 5.0.2 on 2024-02-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0007_rename_buttoncontent_optioncontent_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='contents',
            field=models.ManyToManyField(blank=True, null=True, to='kiosk.optioncontent'),
        ),
        migrations.AlterField(
            model_name='optioncontent',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
