# Generated by Django 5.0.2 on 2024-02-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0008_alter_option_contents_alter_optioncontent_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='quantity',
            field=models.IntegerField(default=1, max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='totalQuantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
